server:
  port: 8888
spring:
  application:
    name: eureka-server-88

# 单机配置
#eureka:
#  client:
#    fetch-registry: false # 是否需要从eureka获取注册信息
#    register-with-eureka: false # 是否需要把该服务注册到eureka
#    service-url: # 暴露注册信息
#      defaultZone: http://127.0.0.1:${server.port}/eureka

# 集群配置
eureka:
  client:
    fetch-registry: true # 是否需要从eureka获取注册信息
    register-with-eureka: true # 是否需要把该服务注册到eureka
    service-url: # 暴露注册信息
      defaultZone: http://127.0.0.1:9999/eureka

#eureka:
#  client:
#    fetch-registry: true # 是否需要从eureka获取注册信息
#    register-with-eureka: true # 是否需要把该服务注册到eureka
#    service-url: # 暴露注册信息
#      defaultZone: http://127.0.0.1:8888/eureka

  instance:
    prefer-ip-address: true # 优先使用ip地址注册到eureka
    lease-expiration-duration-in-seconds: 90 # 服务失效时间，如果90秒没发送心跳，说明服务失效
    lease-renewal-interval-in-seconds: 30  # 服务续约（发送心跳）间隔时间